name: Minegram
author: Cadiducho
version: ${project.version}
main: com.cadiducho.minegram.MinegramPlugin
descripcion: Telegram Bot API implementation to Bukkit
commands: 
    minegram:
        description: Main command
